### ISSUE TITLE
List app versions

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal-ui#379]
To be able to see who and when changed the app. I am especially interested usually who made a app public:)
Some diffs of changes would be nice, maybe some simple json diff like in KBC UI.

**Comment by ujovlado** [comment]
I decided to implement this only for admins and through "list app changes" API call https://kebooladeveloperportal.docs.apiary.io/#reference/0/admin-apps/list-app-changes,  since it provides changes per attribute and diff can be displayed easier.

Later, we can add similar functionality to "home" module ...
